### PR TITLE
Use streamer image as a part of the link to stream.

### PR DESCRIPTION
**Pull request by Uhkis**
I was getting annoyed with those streamer images being "fake links", this PR makes them actually clickable links.

### CODE REVIEW

**Comment by coffenbacher** [comment]
Awesome! Thanks @Uhkis, I noticed that as well. I will deploy the update this weekend.

**Comment by coffenbacher** [comment]
@Uhkis do you want to add yourself, or me to add you (which flag), as a contributor as well? Thanks for the bug report+fix.

**Comment by Uhkis** [comment]
You can add my name there if you want, I'm fine either way.

**Comment by Uhkis** [comment]
Actually yes, add me. Finnish flag for nations cup grand final hype :)

**Comment by coffenbacher** [comment]
Perfect! You'll match the Winland flags for the final

**Comment by Uhkis** [comment]
So, are you gonna update before the final? 😄

**Comment by coffenbacher** [comment]
Sorry @Uhkis , life got in the way. I just deployed now 😆 just in time for Winland to win Battle of Africa right?

**Pull request merged**
